


services:
  database:
    image: 'postgres:latest'
    ports: 
      - 5890:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvc 
    volumes:
      - mvc-database:/var/lib/postgresql/

volumes:
  mvc-database:
